name: Tests
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-variant: ['BC', 'CS']
        racket-version: ['stable', 'current']
    name: Test on Racket ${{ matrix.racket-version }} ${{ matrix.racket-variant }}
    steps:
      - name: Checkout splitflap repo
        uses: actions/checkout@master
      - name: Install Racket ${{ matrix.racket-version }} ${{ matrix.racket-variant }}
        uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Install splitflap lib and dependencies
        run: raco pkg install --auto --batch --link splitflap-lib/
      - name: Run tests
        run: raco test splitflap-tests
      - name: Build docs
        run: raco pkg install --auto --batch --link splitflap-doc/
